---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: ubuntu-16
  driver:
    image: dokken/ubuntu-16.04
    privileged: true
    pid_one_command: /lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
  run_list:
  - recipe[apt]
  attributes:
    apt:
      compile_time_update: true
- name: centos-7
  driver:
    image: dokken/centos-7
    privileged: true
    pid_one_command: /usr/lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
- name: centos-6
  driver:
    image: dokken/centos-6

suites:
  - name: reporting
    run_list:
      - recipe[unit::reporting]
  - name: status
    run_list:
      - recipe[unit::status]
  - name: uploader
    run_list:
      - recipe[unit::uploader]
