dist: trusty
sudo: required
group: edge
services: docker
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

env:
  matrix:
  - T=reporting
  - T=status
  - T=uploader

install: echo "skip bundle install"

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/rspec --version
  - /bin/bash -xe travis/pre-commit.sh
  - /opt/chefdk/embedded/bin/kitchen test $T -d always

notifications:
  email:
    recipients:
      - dmlb2000@gmail.com
      - gitbytes@gmail.com
    on_failure: never
    on_success: always
